stages: 
    - test
    - build
    - deploy

default:
  image: gradle:jdk11

before_script: 
    - echo "Start CI/CD"


test:
    stage: test
    script:
        - echo "Testing fase"
        - chmod +x gradlew
        - ./gradlew test
    only:
        - merge_requests

build: 
    stage: build
    script:
        - echo "Buidling fase"
        - chmod +x gradlew
        - ./gradlew build
    artifacts:
        paths:
            - build/libs/*.jar
        expire_in: 1 week
    only:
        - master

deploy: 
    stage: deploy
    image:
        name: gcr.io/kaniko-project/executor:debug
        entrypoint: [""]
    script:
        - echo "Deploying image"
        - mkdir -p /kaniko/.docker
        - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
        - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    only:
        - master
    
after_script:
    - echo "Einde CI/CD"
